### ISSUE TITLE
Result of select should be Promise<string>

### ISSUE THREAD

**Issue by ncukondo** [TopCli/prompts#80]
Currently, type of select is `select(message: string, options: SelectOptions): Promise<string[]>`. But it actually returns Promise<string>. Type definition should be updated to `select(message: string, options: SelectOptions): Promise<string>`.

**Comment by PierreDemailly** [comment]
Indeed, thanks for reporting.

`PromptAgent` is source of this conflict, I think we should cast its return type.
If you want to open a PR enjoy it, otherwise it should be fixed it in the day.

**Comment by ncukondo** [comment]
Thank you for adding me as a contributor. I have confirmed that the issue has been fixed in PR #84.
