### ISSUE TITLE
Add an option to hide multiselect's tips

### ISSUE THREAD

**Issue by PierreDemailly** [TopCli/prompts#85]
The idea is to add a new option to hide the tip as shown in this screenshot:

![image](https://github.com/TopCli/prompts/assets/39910767/02e4a1bb-b593-4e82-9c60-b517c9ca6e3a)

Could be either
- a boolean `showTip` truthy by default
- a boolean `hideTip` falsy by default

**Comment by PierreDemailly** [comment]
Could also be `hideHint`/`showHint` since we use the term `hint` in the code.

**Comment by FredGuiou** [comment]
I take it ! Can you assign me @PierreDemailly please ?
